name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24' # Specify the Go version you need

    - name: Install dependencies
      run: make deps

    - name: Install tools
      run: make tools

    - name: Lint
      run: make lint

    - name: Run tests
      run: make test

    - name: Generate coverage
      run: make coverage

    - name: Build
      run: make build

    - name: Build for all platforms
      run: make build-all

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/
