
name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Artifacts
    uses: ./.github/workflows/build-artifact.yaml
  release:
    needs: build
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: build/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (Linux AMD64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/deadlinkr-linux-amd64
        asset_name: deadlinkr-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (Linux ARM64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/deadlinkr-linux-arm64
        asset_name: deadlinkr-linux-arm64
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (macOS AMD64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/deadlinkr-darwin-amd64
        asset_name: deadlinkr-darwin-amd64
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (macOS ARM64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/deadlinkr-darwin-arm64
        asset_name: deadlinkr-darwin-arm64
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (Windows AMD64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/deadlinkr-windows-amd64.exe
        asset_name: deadlinkr-windows-amd64.exe
        asset_content_type: application/octet-stream
